#! /bin/sh
# PaperCut QA Test No. 004
# $Revision: 1.1 $
#
# (what am I here for?)
#
# Copyright (c) 2020 (who wrote me?).  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
SCRIPT_DIR=$(cd $(dirname $0) && pwd)
. ${SCRIPT_DIR}/common.test

tmp=$(mktemp -t pc-tests-$seq)
here=`pwd`
status=0	# success is the default!
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
echo "Start of $seq.log" >$seq.log
for i in {10..30}; do
  echo "----------"
  echo ""
  go run test_logfile.go 4 $i 2>>$seq.log
done
